drop table if exists users, items, bookings, requests, comments;

create table if not exists users (
                                    id    bigint generated by default as identity not null
                                        constraint users_pk primary key,
                                    name  varchar(255) not null,
                                    email varchar(255) not null,
                                    UNIQUE (email)
);

create table if not exists items (
                                    id         bigint generated by default as identity not null
                                        constraint items_pk primary key,
                                    name        varchar(255)  not null,
                                    description varchar(2000) not null,
                                    available   boolean       not null,
                                    owner_id    integer       not null
                                        constraint items_users_id_fk references users,
                                    request_id     integer
);

create table if not exists bookings (
                                    id         bigint generated by default as identity not null
                                        constraint bookings_pk primary key,
                                    item_id    bigint      not null
                                        constraint bookings_items_id_fk references items,
                                    start_date timestamp        not null,
                                    end_date   timestamp        not null,
                                    user_id    bigint      not null
                                        constraint bookings_users_id_fk references users,
                                    status     varchar(50) not null
);

create table if not exists requests (
                                    id            bigint generated by default as identity not null
                                        constraint requests_pk primary key,
                                    description   varchar(2000) not null,
                                    requestor_id  bigint        not null
                                        constraint requests_users_id_fk references users,
                                    creation_date date          not null
);

create table if not exists comments (
                                    id        bigint generated by default as identity not null
                                        constraint comments_pk primary key,
                                    item_id   bigint        not null
                                        constraint comments_items_id_fk references items,
                                    user_id bigint        not null
                                        constraint comments_users_id_fk references users,
                                    text      varchar(2000) not null,
                                    created     timestamp    not null
);